apiVersion: 1

datasources:
  - name: Prometheus-pfSense
    type: prometheus
    access: proxy
    uid: prometheus-pfsense
    url: http://prometheus-pfsense:9090
    isDefault: true
    jsonData:
      timeInterval: 30s
